[general]
import = ["~/.config/alacritty/themes/themes/hyper.toml"]
# import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "M+1Code Nerd Font"
style = "Bold"

[font.italic]
family = "M+1Code Nerd Font"
style = "ExtraLight"

[font.normal]
family = "M+1Code Nerd Font"
style = "Regular"

[window]
# decorations = "buttonless"
dynamic_padding = true
opacity = 0.98
# opacity = 0.9
# opacity = 0.75

[window.padding]
x = 25
y = 20
